image: node:10.16

# cache:
#   paths:
#   - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run lint

pages:
  stage: deploy
  script:
    - npm run build
    - mkdir public
    - sed -i 's+/dist/+./dist/+g' dist/bundle.js
    - cp -r dist public/
    - cp -r index.html public/
  artifacts:
    paths:
      - public
  only: 
    - master